'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/collective-consciousness (source: WEB7 Symbiosis WebAPI CollectiveConsciousnessController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class CollectiveConsciousnessModule {
  constructor(http) {
    this._http = http;

    // POST v1/collective-consciousness/spaces (query: name)
    this.createSpace = makeOperation(http, "v1/collective-consciousness", "POST", "spaces", {"query":["name"]});
    // GET v1/collective-consciousness/spaces/{spaceId}/field
    this.getAggregateField = makeOperation(http, "v1/collective-consciousness", "GET", "spaces/{spaceId}/field");
    // POST v1/collective-consciousness/spaces/{spaceId}/join/{sessionId}
    this.joinSpace = makeOperation(http, "v1/collective-consciousness", "POST", "spaces/{spaceId}/join/{sessionId}");
  }
}

module.exports = { CollectiveConsciousnessModule };
