// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class CollectiveConsciousnessModule {
  constructor(http: unknown);

  /** POST v1/collective-consciousness/spaces (query: name) */
  createSpace(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/collective-consciousness/spaces/{spaceId}/field */
  getAggregateField(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/collective-consciousness/spaces/{spaceId}/join/{sessionId} */
  joinSpace(args?: Record<string, any>): Promise<OASISResponse>;
}
