'use strict';

// AUTO-GENERATED by scripts/generate-modules.js - do not hand-edit.
const { CollectiveConsciousnessModule } = require('./CollectiveConsciousness');
const { SymbiosisModule } = require('./Symbiosis');

/**
 * Attaches every generated module to the client under its lowerCamel controller
 * name (e.g. client.completion, client.images, client.holonicMemory).
 */
function attachGeneratedModules(client, http) {
  client.collectiveConsciousness = client.collectiveConsciousness || new CollectiveConsciousnessModule(http);
  client.symbiosis = client.symbiosis || new SymbiosisModule(http);
  return client;
}

module.exports = { attachGeneratedModules };
