// AUTO-GENERATED by scripts/generate-types.js - do not hand-edit.
import type { OASISResponse } from '../core/types';

export declare class SymbiosisModule {
  constructor(http: unknown);

  /** POST v1/symbiosis/sessions/{sessionId}/end */
  endSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** GET v1/symbiosis/sessions/{sessionId} */
  getSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/symbiosis/sessions */
  startSession(args?: Record<string, any>): Promise<OASISResponse>;

  /** POST v1/symbiosis/sessions/{sessionId}/signals */
  submitSignals(args?: Record<string, any>): Promise<OASISResponse>;
}
