'use strict';

// AUTO-GENERATED by scripts/generate-modules.js from endpoints.json - do not hand-edit.
// Regenerate with: node scripts/generate-modules.js

const { makeOperation } = require('../core/routeHelper');

/**
 * Generated wrapper for v1/symbiosis (source: WEB7 Symbiosis WebAPI SymbiosisController.cs).
 * Every method takes a single args object: path-template tokens (e.g. {id})
 * are consumed from it automatically; any remaining keys are sent as the
 * query string (GET/DELETE) or JSON body (POST/PUT).
 */
class SymbiosisModule {
  constructor(http) {
    this._http = http;

    // post v1/symbiosis/sessions/{sessionId}/end
    this.endSession = makeOperation(http, "v1/symbiosis", "POST", "sessions/{sessionId}/end");
    // get v1/symbiosis/sessions/{sessionId}
    this.getSession = makeOperation(http, "v1/symbiosis", "GET", "sessions/{sessionId}");
    // post v1/symbiosis/sessions
    this.startSession = makeOperation(http, "v1/symbiosis", "POST", "sessions");
    // post v1/symbiosis/sessions/{sessionId}/signals
    this.submitSignals = makeOperation(http, "v1/symbiosis", "POST", "sessions/{sessionId}/signals");
  }
}

module.exports = { SymbiosisModule };
